zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181"
kafka:
  image: wurstmeister/kafka:0.9.0.1
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
manager:
  image: sheepkiller/kafka-manager
  links:
    - zookeeper:zk
  environment:
    ZK_HOSTS: zk:2181
    APPLICATION_SECRET: tester
  ports:
    - "9000:9000"
